"""
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if not s:
            return t
        
        sorted_s = sorted(s)
        sorted_t = sorted(t)
        s_len = len(sorted_s)

        i = 0

        while i < s_len:
            if sorted_s[i] != sorted_t[i]:
                return sorted_t[i]
            
            i += 1
        
        return sorted_t[i]
    

s = Solution()
print(s.findTheDifference("abcd", "abcde"))
print(s.findTheDifference("", "y"))
print(s.findTheDifference("ae", "aea"))
